-- Calendar Events Seed Data
-- Generated on 2026-06-04T06:28:03.759Z
-- Run this in Supabase Dashboard > SQL Editor

BEGIN;

-- Clear existing data (safe to re-run)
DELETE FROM public.event_attachments;
DELETE FROM public.recurring_event_exceptions;
DELETE FROM public.calendar_events;

-- Insert recurring event templates
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('5ed482fa-5fa8-469d-9884-b18db3be7738', 'Branch Assembly', NULL, '2026-05-02', NULL, '09:00', '12:00', false, 'TOLIA Main Office', NULL, 'meeting', 'published', 'Branch Manager', true, 'First Saturday of every month', 'FREQ=MONTHLY;BYDAY=1SA', NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('4ddd4494-a919-4161-a8ad-b3755c22ccd1', 'Green Hour Weekly Training', NULL, '2026-05-04', NULL, '10:00', '11:00', false, NULL, NULL, 'training', 'published', NULL, true, 'Every Monday', 'FREQ=WEEKLY;BYDAY=MO', NULL, NULL);

-- Insert one-off events
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('1a0ae181-172b-4aaa-bbdc-50dee3050a2e', 'Branch Managers Meeting', 'Monthly branch performance review and target setting.', '2026-05-20', NULL, '14:00', '16:00', false, 'Conference Room A', NULL, 'meeting', 'published', 'Branch Manager', false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('1eec7265-730d-4fff-ade5-58a091879183', 'New Agent Orientation', 'Mandatory orientation for all new agents. Bring government IDs and contract documents.', '2026-05-18', NULL, '14:00', '16:00', false, 'TOLIA Training Room', NULL, 'training', 'published', 'HR Department', false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('f372ca6e-7c18-4bb9-8ccd-afd7637d93cf', 'Policy Submission Reminder', 'All pending policy submissions must be encoded by end of day.', '2026-05-18', NULL, NULL, NULL, true, NULL, NULL, 'deadline', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('9f94dd75-82ee-4da4-8f88-1960d9fb703f', 'One-on-One Coaching Session', NULL, '2026-05-19', NULL, '09:00', '10:00', false, 'Unit Manager''s Office', NULL, 'meeting', 'published', 'Unit Manager', false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('882af487-8722-405f-848b-fd46c1fc6ea8', 'Social Media Content Deadline', 'Submit May content cards for approval.', '2026-05-19', NULL, '17:00', NULL, false, NULL, NULL, 'deadline', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('ca441182-8146-4b33-8e8d-a8073b12ba97', 'Compliance Refresher', 'Annual compliance and code of ethics refresher course.', '2026-05-20', NULL, '09:00', '10:30', false, 'Conference Room B', NULL, 'training', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('764267db-d7f7-45fe-868b-4069921d8ece', 'May Birthday Celebration', 'Celebrating May-born team members!', '2026-05-20', NULL, '16:00', '17:00', false, 'Lounge Area', NULL, 'social', 'published', 'Social Committee', false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('14bfb6c8-7ba3-43d8-9743-43d419c06554', 'Leadership Workshop', 'Situational leadership and team motivation techniques.', '2026-05-21', NULL, '13:00', '15:00', false, 'Training Center', NULL, 'training', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('4f45c692-9212-42d7-82ba-d2c2eec8b01d', 'BYB Session', 'Build Your Business (BYB) training and assessment session.', '2026-05-22', NULL, '09:00', '12:00', false, 'TOLIA Branch Office', NULL, 'exam', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('85752eba-cbc8-45ab-98d6-abde45f1a749', 'Team Lunch', NULL, '2026-05-22', NULL, '12:00', '13:30', false, 'Café TOLIA', NULL, 'social', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('8fe1c1d5-4a10-4104-88e8-b37cef1bba36', 'Licensing Exam', 'Pre-licensing examination for new agents. Bring valid ID and notice of admission.', '2026-05-25', NULL, '08:00', '12:00', false, 'Testing Center', NULL, 'exam', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('2548740b-e303-47bb-9f1f-0791bc4d8f98', 'Unit Performance Review', NULL, '2026-05-25', NULL, '15:00', '16:30', false, 'Unit Manager''s Office', NULL, 'meeting', 'published', 'Unit Manager', false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('82fc744d-f161-43d1-8c9d-3f49b5706ddc', 'Claims Processing Seminar', 'Updates on claims processing workflow and documentation.', '2026-05-27', NULL, '09:00', '11:00', false, 'Seminar Hall', NULL, 'training', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('9cda028b-4183-4253-b704-cff811563de0', 'Recruitment Strategy Huddle', NULL, '2026-05-28', NULL, '10:00', '11:30', false, NULL, NULL, 'meeting', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('3c566668-0eb5-4ae4-ac63-7d61fcc176b0', 'MDRT Qualification Check-In', 'Track MDRT qualification progress and address gaps.', '2026-05-28', NULL, '14:00', '15:00', false, NULL, NULL, 'meeting', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('478616af-3ca9-4b2d-8d1a-a5ead3d12056', 'Weekend Kickoff Huddle', 'End-of-week motivation and target check.', '2026-05-29', NULL, '09:00', '10:00', false, 'Main Office', NULL, 'meeting', 'published', 'Branch Manager', false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('93d842bd-2314-491a-8731-e7787237a117', 'PRU Life UK Online Module Due', 'Complete PRU Life UK Module 3: Needs Analysis.', '2026-05-29', NULL, NULL, NULL, true, NULL, NULL, 'deadline', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('809d06df-4b71-4198-93d8-8f7a85049448', 'Company Incentive Deadline', 'Final day to qualify for the Q2 production incentive.', '2026-05-30', NULL, '17:00', NULL, false, NULL, NULL, 'deadline', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('58657704-52ee-47b5-90ef-43850929a282', 'Weekend Outreach Program', 'Community outreach and financial literacy seminar for barangay residents.', '2026-05-30', NULL, '08:00', '12:00', false, 'Community Center', NULL, 'social', 'published', 'Social Committee', false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('a5f44425-832a-4cd2-87dd-0262906631eb', 'Branch Managers Meeting', NULL, '2026-06-03', NULL, '14:00', '16:00', false, NULL, NULL, 'meeting', 'published', 'Branch Manager', false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('5230c978-a463-44c2-bbec-20dde4c0d0d3', 'Product Training - PruLink Prime', 'In-depth product training on the new PruLink Prime investment-linked plan.', '2026-06-01', NULL, '10:00', '12:00', false, NULL, NULL, 'training', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('7aa12b5f-07ce-446c-bffb-fba2249bc773', 'Insurance Code of Ethics', NULL, '2026-06-03', NULL, '09:00', '11:00', false, 'Training Room A', NULL, 'training', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('abb2ccb7-5ee7-4fd3-ae82-27f9294df24f', 'Recruitment Week Campaign', 'Branch-wide recruitment drive. All agents encouraged to invite prospects. Prizes for top referrer.', '2026-06-01', '2026-06-05', NULL, NULL, true, NULL, NULL, 'social', 'published', 'Branch Manager', false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('04a3f53b-5a6f-4d94-9026-92ce0fe2343a', 'Team Building Activity', 'Annual team building and bonding activity.', '2026-06-05', NULL, '08:00', '17:00', false, 'Venue TBA', NULL, 'social', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('c2a7e68f-d2f3-4b98-a541-75ec6a5b1559', 'BYB Session', NULL, '2026-06-05', NULL, '09:00', '12:00', false, 'TOLIA Branch Office', NULL, 'exam', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('3bdc358e-7c7d-4b38-b5ab-d12c42cce5bd', 'Unit Leaders Meeting', NULL, '2026-06-08', NULL, '13:00', '14:30', false, NULL, NULL, 'meeting', 'published', 'Unit Manager', false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('c30d62ed-d878-4d5f-9ec4-e26b20dce065', 'Quarterly Report Deadline', 'Submit Q2 performance reports to the branch office.', '2026-06-08', NULL, '17:00', NULL, false, NULL, NULL, 'deadline', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('501b95c0-c71c-41a1-8c13-6ac9dd24509e', 'Mid-Year Planning Workshop', 'Three-day strategic planning workshop for all unit managers and branch leaders. Hotel accommodation provided.', '2026-06-08', '2026-06-10', '09:00', '17:00', false, 'Conference Center', NULL, 'meeting', 'published', 'Branch Manager', false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('76ee0a8d-e7e3-49cb-872e-d21dd106dec5', 'Prospecting Workshop', 'Effective prospecting techniques and lead generation strategies.', '2026-06-11', NULL, '09:00', '11:00', false, 'Training Center', NULL, 'training', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('f692553d-7aff-434d-8a2a-8cddc0562aea', 'Recruiting Bootcamp', 'Intensive recruiting skills bootcamp. Role-playing and objection handling.', '2026-06-12', NULL, '09:00', '12:00', false, 'Seminar Hall', NULL, 'training', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('9b42b108-0c2f-43b9-8a27-b9ad975e74e8', 'Social Committee Planning', NULL, '2026-06-12', NULL, '14:00', '15:00', false, NULL, NULL, 'meeting', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('af077769-733d-48e0-a1c3-a95a1c5951e4', 'MDRT Application Deadline', 'Final submission of MDRT qualification documents.', '2026-06-15', NULL, NULL, NULL, true, NULL, NULL, 'deadline', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('7c74e3fe-e2e3-4f7c-aa4b-2042b89bf9bf', 'Underwriting Updates', 'Latest underwriting guidelines and frequently asked cases.', '2026-06-17', NULL, '10:00', '11:30', false, 'Conference Room', NULL, 'training', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('db2632fa-ddb3-4f85-a3bd-cdf1a1f35c60', 'Month-End Sales Push', 'Final sales push day. Extended office hours, free dinner for top performers.', '2026-06-19', NULL, '08:00', '17:00', false, 'All Branches', NULL, 'social', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('22969363-4a97-42c3-8545-0ff8eb9dba7b', 'Licensing Exam (Batch 2)', NULL, '2026-06-19', NULL, '13:00', '16:00', false, 'Testing Center', NULL, 'exam', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('5ca86528-50af-46e1-b391-cd483e31da3b', 'Agent Recognition Awards', 'Quarterly awards ceremony recognizing top-performing agents.', '2026-06-19', NULL, '17:30', '19:00', false, 'Grand Ballroom', NULL, 'social', 'published', 'Branch Manager', false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('400939f8-90d5-4a8d-90be-97c79fa46c98', 'Policy Conversion Workshop', NULL, '2026-06-22', NULL, '14:00', '16:00', false, 'Training Room B', NULL, 'training', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('de55d737-c599-42c7-b9ea-7d76fb9794b5', 'TOLIA Agency Convention', 'Annual agency convention. All agents required to attend. Bus transportation provided from branch office.', '2026-06-25', '2026-06-27', NULL, NULL, true, 'Batangas Convention Center', NULL, 'social', 'published', 'Branch Manager', false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('c39f0a40-939e-476e-af60-46490ce230f3', 'Financial Literacy Seminar', NULL, '2026-06-26', NULL, '09:00', '11:00', false, 'Seminar Hall', NULL, 'training', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('155dfd12-425d-4759-a271-361e59233ec3', 'Team Happy Hour', NULL, '2026-06-26', NULL, '16:00', '18:00', false, 'Rooftop Lounge', NULL, 'social', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('29597676-76c7-444e-95da-d556f865d3ea', 'End-of-Month Performance Review', 'Month-end review of individual and unit performance targets.', '2026-06-29', NULL, '15:00', '17:00', false, NULL, NULL, 'meeting', 'published', 'Unit Manager', false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('37da0bec-2f52-4e0d-8ffb-1c28a93c3f12', 'Enrollment Deadline - FYI', 'Final day to enroll clients under the FYI (First Year Incentive) program.', '2026-06-30', NULL, '17:00', NULL, false, NULL, NULL, 'deadline', 'published', NULL, false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('dd0c34d1-ea14-4d3b-8f47-2c5450f1f2f4', 'Mid-Year Goal Setting', 'Set H2 goals and action plans with your unit manager.', '2026-06-30', NULL, '09:00', '11:00', false, 'Conference Room A', NULL, 'meeting', 'published', 'Unit Manager', false, NULL, NULL, NULL, NULL);
INSERT INTO public.calendar_events (id, title, description, date, end_date, start_time, end_time, all_day, location, location_url, event_type, status, organizer, is_recurring, recurring_pattern, rrule, registration_url, href)
VALUES ('0c2f0b8a-e0f4-4bfc-b64f-7a6681f1debb', 'Product Knowledge Bootcamp', 'Three-day intensive product training covering all Pru Life UK products. Certification required for all agents.', '2026-07-06', '2026-07-08', '09:00', '17:00', false, 'Training Center', NULL, 'training', 'published', 'Training Department', false, NULL, NULL, NULL, NULL);

-- Insert event attachments
INSERT INTO public.event_attachments (id, event_id, name, url, type) VALUES ('10fa81b8-9bdb-44d1-b8ae-4ba8bbac3348', '14bfb6c8-7ba3-43d8-9743-43d419c06554', 'Workshop Slides', '#', 'pdf');
INSERT INTO public.event_attachments (id, event_id, name, url, type) VALUES ('8cae4830-03a1-46fc-b5be-b304182f62d8', '14bfb6c8-7ba3-43d8-9743-43d419c06554', 'Handout', '#', 'pdf');
INSERT INTO public.event_attachments (id, event_id, name, url, type) VALUES ('e8387864-1151-4bcd-8f39-0451096629cd', '5230c978-a463-44c2-bbec-20dde4c0d0d3', 'PruLink Prime Brochure', '#', 'pdf');
INSERT INTO public.event_attachments (id, event_id, name, url, type) VALUES ('0d25b68e-8420-4904-aaa6-d2d4817612b6', '5230c978-a463-44c2-bbec-20dde4c0d0d3', 'Product Illustrations', '#', 'doc');
INSERT INTO public.event_attachments (id, event_id, name, url, type) VALUES ('4ab4e87d-6d1b-41e9-8e4f-2d84c876ef61', '501b95c0-c71c-41a1-8c13-6ac9dd24509e', 'Planning Agenda', '#', 'pdf');
INSERT INTO public.event_attachments (id, event_id, name, url, type) VALUES ('2edf7294-1f45-418d-a5f3-799153ac6d4a', '501b95c0-c71c-41a1-8c13-6ac9dd24509e', 'Hotel Info', '#', 'link');
INSERT INTO public.event_attachments (id, event_id, name, url, type) VALUES ('83421495-2cc8-4135-97b7-7f32f91543e8', 'f692553d-7aff-434d-8a2a-8cddc0562aea', 'Bootcamp Workbook', '#', 'pdf');
INSERT INTO public.event_attachments (id, event_id, name, url, type) VALUES ('473b7145-559d-42c8-9217-7ffa6c8c2b27', '7c74e3fe-e2e3-4f7c-aa4b-2042b89bf9bf', 'Underwriting Guide v3', '#', 'pdf');
INSERT INTO public.event_attachments (id, event_id, name, url, type) VALUES ('97e3af7e-e50f-47b2-9d2a-fb002d85b4cd', '400939f8-90d5-4a8d-90be-97c79fa46c98', 'Conversion Checklist', '#', 'pdf');
INSERT INTO public.event_attachments (id, event_id, name, url, type) VALUES ('d1027a23-9f52-4d4a-8924-2687632e27e5', '400939f8-90d5-4a8d-90be-97c79fa46c98', 'Sample Scenarios', '#', 'doc');
INSERT INTO public.event_attachments (id, event_id, name, url, type) VALUES ('afac890b-f425-4061-a91b-4e2bde0c5915', 'de55d737-c599-42c7-b9ea-7d76fb9794b5', 'Convention Program', '#', 'pdf');
INSERT INTO public.event_attachments (id, event_id, name, url, type) VALUES ('9febd987-370e-4537-8a35-b7672cf32842', 'de55d737-c599-42c7-b9ea-7d76fb9794b5', 'Hotel Room Assignment', '#', 'doc');
INSERT INTO public.event_attachments (id, event_id, name, url, type) VALUES ('bde2f358-c083-4b0d-800d-947f203e7661', 'de55d737-c599-42c7-b9ea-7d76fb9794b5', 'Transportation Schedule', '#', 'link');
INSERT INTO public.event_attachments (id, event_id, name, url, type) VALUES ('686ec946-3234-4af1-bdcf-7dd849cc80c6', '0c2f0b8a-e0f4-4bfc-b64f-7a6681f1debb', 'Bootcamp Schedule', '#', 'pdf');
INSERT INTO public.event_attachments (id, event_id, name, url, type) VALUES ('1c3b5447-6ced-4def-8ebe-ea3e7fdefd97', '0c2f0b8a-e0f4-4bfc-b64f-7a6681f1debb', 'Pre-Reading Materials', '#', 'pdf');

COMMIT;
